Fix python argparse issue when running with --help
When running python tf_cnn_benchmarks.py --help I was getting
TypeError: %o format: a number is required, not dict

argparse has an issue to recognize single % in the help message
of an argument. The solution is to double the percent character.